Repository SOPT-33-iOS-Team-1/SOPKATHON_33-Server, pull requests merged in 2023-11, with the labels that each got.

#2 feat: 초기 프로젝트 설정
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/sopt/sopkerton/SopkertonApplication.java
Labels: ✨Feat, 승환🍪, 🔥 Pull Request

#6 Feat/#5 create common objects
  src/main/java/org/sopt/sopkerton/common/exception/GlobalError.java
  src/main/java/org/sopt/sopkerton/common/exception/GlobalException.java
  src/main/java/org/sopt/sopkerton/common/exception/GlobalSuccess.java
  src/main/java/org/sopt/sopkerton/common/exception/base/ErrorBase.java
  src/main/java/org/sopt/sopkerton/common/exception/base/ExceptionBase.java
  src/main/java/org/sopt/sopkerton/common/exception/base/RootEnum.java
  src/main/java/org/sopt/sopkerton/common/exception/base/SuccessBase.java
  src/main/java/org/sopt/sopkerton/common/response/ApiResponse.java
  src/main/java/org/sopt/sopkerton/common/response/CommonControllerAdvice.java
Labels: ✨Feat, 동규 햄🐹

#8 Docs/#7 mission readme (1차)
  README.md
Labels: 동규 햄🐹, 📃Docs

#12 feat: 봉사 프로그램, 취업 프로그램 엔티티 생성
  README.md
  src/main/java/org/sopt/sopkerton/common/domain/BaseEntity.java
  src/main/java/org/sopt/sopkerton/program/domain/Category.java
  src/main/java/org/sopt/sopkerton/program/domain/Employment.java
  src/main/java/org/sopt/sopkerton/program/domain/Program.java
  src/main/java/org/sopt/sopkerton/program/domain/Volunteering.java
Labels: ☁️Database, 승환🍪, 🔥 Pull Request

#14 Feat/#11 get main view
  src/main/java/org/sopt/sopkerton/common/response/ApiResponse.java
  src/main/java/org/sopt/sopkerton/user/controller/UserController.java
  src/main/java/org/sopt/sopkerton/user/domain/User.java
  src/main/java/org/sopt/sopkerton/user/domain/enums/Gender.java
  src/main/java/org/sopt/sopkerton/user/domain/exception/UserError.java
  src/main/java/org/sopt/sopkerton/user/domain/exception/UserException.java
  src/main/java/org/sopt/sopkerton/user/domain/exception/UserSuccess.java
  src/main/java/org/sopt/sopkerton/user/dto/response/MainView.java
  src/main/java/org/sopt/sopkerton/user/infrastructure/UserRepository.java
  src/main/java/org/sopt/sopkerton/user/service/UserService.java
Labels: 🪄API, ✨Feat, 동규 햄🐹

#16 Feat/#15 get user detail
  src/main/java/org/sopt/sopkerton/user/controller/UserController.java
  src/main/java/org/sopt/sopkerton/user/domain/exception/UserSuccess.java
  src/main/java/org/sopt/sopkerton/user/dto/response/DetailView.java
  src/main/java/org/sopt/sopkerton/user/service/UserService.java
Labels: 🪄API, ✨Feat, 동규 햄🐹
